model:
  random_seed: 1411601911522923973
  learning_task: NODE_CLASSIFICATION
  encoder:
    use_incoming_nbrs: true
    use_outgoing_nbrs: true
    layers:
    - - type: FEATURE
        options: {}
        input_dim: -1
        output_dim: 128
        init:
          type: GLOROT_NORMAL
          options: {}
        optimizer:
          type: DEFAULT
          options:
            learning_rate: 0.1
            eps: 1.0e-10
            init_value: 0.0
            lr_decay: 0.0
            weight_decay: 0.0
        bias: false
        bias_init:
          type: ZEROS
          options: {}
        activation: NONE
    - - type: GNN
        options:
          type: GRAPH_SAGE
          aggregator: MEAN
        input_dim: 128
        output_dim: 128
        init:
          type: GLOROT_NORMAL
          options: {}
        optimizer:
          type: DEFAULT
          options:
            learning_rate: 0.1
            eps: 1.0e-10
            init_value: 0.0
            lr_decay: 0.0
            weight_decay: 0.0
        bias: true
        bias_init:
          type: ZEROS
          options: {}
        activation: RELU
    - - type: GNN
        options:
          type: GRAPH_SAGE
          aggregator: MEAN
        input_dim: 128
        output_dim: 128
        init:
          type: GLOROT_NORMAL
          options: {}
        optimizer:
          type: DEFAULT
          options:
            learning_rate: 0.1
            eps: 1.0e-10
            init_value: 0.0
            lr_decay: 0.0
            weight_decay: 0.0
        bias: true
        bias_init:
          type: ZEROS
          options: {}
        activation: RELU
    - - type: GNN
        options:
          type: GRAPH_SAGE
          aggregator: MEAN
        input_dim: 128
        output_dim: 40
        init:
          type: GLOROT_NORMAL
          options: {}
        optimizer:
          type: DEFAULT
          options:
            learning_rate: 0.1
            eps: 1.0e-10
            init_value: 0.0
            lr_decay: 0.0
            weight_decay: 0.0
        bias: true
        bias_init:
          type: ZEROS
          options: {}
        activation: NONE
    train_neighbor_sampling:
    - type: UNIFORM
      options:
        max_neighbors: 15
      use_hashmap_sets: true
    - type: UNIFORM
      options:
        max_neighbors: 10
      use_hashmap_sets: false
    - type: UNIFORM
      options:
        max_neighbors: 5
      use_hashmap_sets: false
    eval_neighbor_sampling:
    - type: UNIFORM
      options:
        max_neighbors: 15
      use_hashmap_sets: true
    - type: UNIFORM
      options:
        max_neighbors: 10
      use_hashmap_sets: false
    - type: UNIFORM
      options:
        max_neighbors: 5
      use_hashmap_sets: false
    embedding_dim: -1
  decoder:
    type: NODE
    options: {}
    optimizer:
      type: ADAGRAD
      options:
        learning_rate: 0.1
        eps: 1.0e-10
        init_value: 0.0
        lr_decay: 0.0
        weight_decay: 0.0
  loss:
    type: CROSS_ENTROPY
    options:
      reduction: MEAN
  dense_optimizer:
    type: ADAM
    options:
      learning_rate: 0.003
      amsgrad: false
      beta_1: 0.9
      beta_2: 0.999
      eps: 1.0e-08
      weight_decay: 0.0
  sparse_optimizer:
    type: ADAGRAD
    options:
      learning_rate: 0.1
      eps: 1.0e-10
      init_value: 0.0
      lr_decay: 0.0
      weight_decay: 0.0
storage:
  device_type: cuda
  device_ids: []
  dataset:
    dataset_dir: /working_dir/marius/datasets/arxiv_example/
    num_edges: 1166243
    num_nodes: 169343
    num_relations: 1
    num_train: 90941
    num_valid: 29799
    num_test: 48603
    node_feature_dim: 128
    rel_feature_dim: -1
    num_classes: 40
    initialized: false
  edges:
    type: FLAT_FILE
    options:
      dtype: int
  nodes:
    type: HOST_MEMORY
    options:
      dtype: int
  embeddings:
    type: DEVICE_MEMORY
    options:
      dtype: float
  features:
    type: PARTITION_BUFFER
    options:
      dtype: float
      num_partitions: 32
      buffer_capacity: 3
      prefetching: true
      fine_to_coarse_ratio: 1
      num_cache_partitions: 0
      edge_bucket_ordering: COMET
      node_partition_ordering: DISPERSED
      randomly_assign_edge_buckets: true
  prefetch: true
  shuffle_input: true
  full_graph_evaluation: false
  export_encoded_nodes: false
  model_dir: /working_dir/marius/datasets/arxiv_example/model_0/
  log_level: info
  train_edges_pre_sorted: false
training:
  batch_size: 1000
  negative_sampling: ???
  num_epochs: 10
  pipeline:
    sync: true
    gpu_sync_interval: 16
    gpu_model_average: true
    staleness_bound: 16
    batch_host_queue_size: 4
    batch_device_queue_size: 4
    gradients_device_queue_size: 4
    gradients_host_queue_size: 4
    batch_loader_threads: 4
    batch_transfer_threads: 2
    compute_threads: 1
    gradient_transfer_threads: 2
    gradient_update_threads: 4
  epochs_per_shuffle: 1
  logs_per_epoch: 2
  save_model: true
  checkpoint:
    save_best: false
    interval: -1
    save_state: false
  resume_training: false
  resume_from_checkpoint: ''
evaluation:
  batch_size: 1000
  negative_sampling: ???
  pipeline:
    sync: true
    gpu_sync_interval: 16
    gpu_model_average: true
    staleness_bound: 16
    batch_host_queue_size: 4
    batch_device_queue_size: 4
    gradients_device_queue_size: 4
    gradients_host_queue_size: 4
    batch_loader_threads: 4
    batch_transfer_threads: 2
    compute_threads: 1
    gradient_transfer_threads: 2
    gradient_update_threads: 4
  epochs_per_eval: 1
  checkpoint_dir: ''
